### ISSUE TITLE
Cannot add waypoints with multiple characters or edit the name of existing waypoints.

### ISSUE THREAD

**Issue by Lantorer1** [QuapiL1/Waypoints#5]
These two things are not working for me, which is a bummer.

I have made GIFs showing the problem.

https://gyazo.com/13c90d0337e8e40aadeb34c311060e8a
https://gyazo.com/c63d50ea42de551a26580cd9a4a8298d

I have also attached the GIFs as files.

https://user-images.githubusercontent.com/86102559/122536206-9446cc80-d024-11eb-9134-871c81d0e415.mp4

https://user-images.githubusercontent.com/86102559/122536212-9577f980-d024-11eb-8826-6d8994ebb3ff.mp4

**Comment by YarinQuapi** [comment]
Hey, renaming a waypoint is currently not supported, and as written in game, that is to change the item in the GUI. As for creating a waypoint, I will find a fix as soon as I am home today. Thanks for reporting the issues.

**Comment by YarinQuapi** [comment]
Hey, I've fixed the issue in the latest update. Thanks for repoting.
https://www.spigotmc.org/resources/qwaypoints.92554/
