### ISSUE TITLE
How do i remove the bar at the bottom showing the direction where to go

### ISSUE THREAD

**Issue by elmu37** [QuapiL1/Waypoints#8]
It just put it there and i cant make it go away
![2022-11-25_22 01 28](https://user-images.githubusercontent.com/119077889/204050471-90117907-74f7-425c-b56b-073c4d33d6c7.png)

**Comment by YarinQuapi** [comment]
Hi, you can remove it by either getting to the destination (10 blocks from the point by default), or by using /wp track off.
